blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://dash.applovin.com/documentation/mediation/react-native/getting-started/integration
    about: Documentation for the AppLovin MAX React Native Module
  - name: Support
    url: https://monetization-support.applovin.com/hc/en-us
    about: Answers to common questions and support for AppLovin MAX
