require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'AppLovinMAXExample' do
  
  # Pull in the native module via its podspec
  pod 'react-native-applovin-max', :path => '../..'

  use_react_native!

  use_native_modules!
end
