require_relative '../node_modules/react-native/scripts/react_native_pods'

# Uncomment the next line to define a global platform for your project
platform :ios, min_ios_version_supported
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'AppLovinMAX' do

  use_react_native!

  pod 'AppLovinSDK', '11.7.0'

end
