/**
 * Plugin properties for Android.
 */
export type AndroidPluginProps = {
    // apiKey for Ad Review.
    adReviewKey?: string;

    // Add mediated ad networks
    dependencies?: {
        // specify a whole repository such as "maven { url \"https://xxx.yyy.zzz\" }"
        repository?: string;
        // specify a whole dependency such as "implementation (\"com.applovin.mediation:xxx:+\")"
        dependency: string;
    }[];

    // Add metadata to <application/> in AndroidManifest.xml
    metaDataManifest?: {
        name: string;
        value: string;
    }[];
};

/**
 * Plugin properties for iOS.
 */
export type iOSPluginProps = {
    // specify a whole dependency such as "pod 'AppLovinMediationXXXAdapter'"
    dependencies?: string[];

    // A file containing a list of SKAdNetwork identifiers that is generated by Info.plist Generator
    // {@link https://developers.applovin.com/en/ios/overview/skadnetwork#infoplist-generator}.
    skAdNetworkIdFile?: string;

    // Add a list of key and value into Info.plist
    infoPlist: {
        key: string;
        value: string | boolean;
    }[];
};

/**
 * Plugin properties for Android and iOS.
 */
export type PluginProps = {
    // Plugin properties for Android.
    android?: AndroidPluginProps;

    // Plugin properties for iOS.
    ios?: iOSPluginProps;
};
